### ISSUE TITLE
JSON with comments in Visual Studio Code

### ISSUE THREAD

**Issue by ww9** [komkom/jsonc#1]
I love this project! I'm sharing something related I just found in Visual Studio code. Hope it helps.

`JSON with Comments (jsonc)` syntax highlighting is available in Visual Studio Code:

![image](https://user-images.githubusercontent.com/27555162/53253132-e961b600-3696-11e9-9526-1538e8b3a5b7.png)

When using default `JSON` syntax highlighting in VSCode it complains about comments and about trailing commas:

![image](https://user-images.githubusercontent.com/27555162/53253088-d0590500-3696-11e9-9894-6cb8dc79264c.png)

After switching to `JSON with Comments (jsonc)` it validates just fine:

![image](https://user-images.githubusercontent.com/27555162/53253624-0ea2f400-3698-11e9-9c4e-14e062463319.png)

This is what I could find about this validation in VSCode: 

Small paragraph in documentation: https://code.visualstudio.com/docs/languages/json#_json-with-comments

It seems that the syntax specification is in: https://github.com/Microsoft/vscode/blob/master/extensions/json/syntaxes/JSONC.tmLanguage.json

Thanks for the project!

**Comment by ww9** [comment]
By the way, I suspect the main reason why we don't have a more ergonomic JSON standard with comments and leniency with trailing commas is because of too much legacy code in parsers and a bit of performance. But this is just a wild guess.

**Comment by komkom** [comment]
Hey it took a while but finally I uploaded a new version which should fix the multi line issue. Thanks for the info about vs code!
