### ISSUE TITLE
Support of multi-line string literal

### ISSUE THREAD

**Issue by jianwu** [komkom/jsonc#2]
I have very similar idea, I always like with minor extension for JSON to make JSON as main stream config language.  Like the way you shared a simple doc about the idea, hopefully JSONC will become a mainstream standard 

One idea to add here is to support multi-line String literal with back quote "`" as what defined in ES6,  the idea is try to make jsonc as compatible as possible with javascript syntax. So for javascript client can just use eval() to parse the doc (similar as jsonp)

**Comment by komkom** [comment]
I fixed the multi line issue. it now transforms line breaks in strings in jsonc to json line breaks "\n". Not sure if this is the best way to do it. What do you think?
