### ISSUE TITLE
The parser did not complain for a multi-line string

### ISSUE THREAD

**Issue by kamathln** [komkom/jsonc#3]
Test case

https://gist.github.com/kamathln/26e43eb9552e03939b942bc57721950f

Note carefully after `give: "[it `: the string extends and gobbles up the comment. The parser did not complain, nor did it give any output. In the Javascript console, All I see is "success"

**Comment by komkom** [comment]
Took a while ... but I uploaded a new version which rewrites line breaks to json line breaks "\n". It should work now. What do you think?
