### ISSUE TITLE
jsonc docker image on docker hub?

### ISSUE THREAD

**Issue by wwuck** [komkom/jsonc#4]
It would be nice to have a jsonc image on docker hub that could be easily used in CI environments, to easily convert jsonc to regular json.

There is a [PR for `jq`](https://github.com/stedolan/jq/pull/2004) that should provide an example of how to implement.

It looks like from reading that PR that you could then enable auto-builds on docker hub that would automatically build a new docker image on hub.docker.com when code is committed to this github repository.

**Comment by komkom** [comment]
I am not sure if I follow. jsonc is just a go module which can be used as a dependency in go projects.

**Comment by wwuck** [comment]
Hmmm I was referring to the `jsonc` [cli program](https://github.com/komkom/jsonc#as-cli).  I would like to be able to use `jsonc` in a CI (jenkins) environment for purposes of linting json files that contain comments.

**Comment by komkom** [comment]
What would you need from my side to make this work?

**Comment by wwuck** [comment]
@komkom sorry for the late response on this...

I'm not a golang user so I just modified the sample Dockerfile from the [official golang docker image](https://hub.docker.com/_/golang/).  It appears to run fine with the alpine image so I've used that for faster runtime.
```dockerfile
# could also use golang:alpine here if specific version is not required
FROM golang:1.16-alpine

# get the latest alpine security updates
RUN apk --no-cache upgrade

WORKDIR /go/src/app
COPY . .

RUN go get -d -v ./...; \
go install -v ./...

# is it possible to change the built executable from `cmd` to `jsonc`?
ENTRYPOINT ["/go/bin/cmd"]
```
Then you can create an account on docker hub and connect it to your github repository here to enable automatic builds of the docker images each time you push commits to github.
https://betterprogramming.pub/build-your-docker-images-automatically-when-you-push-on-github-18e80ece76af

The only thing missing here is that `jsonc` doesn't seem to set a different exit code if I input invalid jsonc content?  Without something like that it doesn't really make sense to use it in a CI context.

**Comment by wwuck** [comment]
I should have also mentioned earlier that my use case here is for linting the [vscode devcontainer.json file](https://code.visualstudio.com/docs/remote/devcontainerjson-reference) which appears to be just regular json with javascript-style `//` comments just like jsonc, although I can't seem to find any reference to comments on the file specs.

I would probably be just using `docker run -i --rm komkom/jsonc -m < devcontainer.json` to convert the jsonc to regular json and then piping that through [`jq`](https://github.com/stedolan/jq), assuming that a docker image gets uploaded to `komkom/jsonc` on docker hub.

**Comment by komkom** [comment]
I guess I found the bug in cmd/main.go. I pushed a commit to master, now you should get a correct error code in the error case.

**Comment by wwuck** [comment]
Thanks for the quick fix.  I can't seem to trigger the error code.

When I run a test on https://komkom.github.io/ with the contents of (including newline):
```
{{

```
I get an error of 
```
error line: 2 pos: 1
```
which seems correct.

However when I install locally I can't trigger any non-zero exit code.

Installed with the latest `go version go1.16.4 linux/amd64` following instructions on github readme: 
```sh
go get github.com/komkom/jsonc/...
```
and running jsonc with
```
/tmp/jsonc-test$ alias jsonc=~/go/bin/cmd
/tmp/jsonc-test$ cat test.jsonc 
{{
/tmp/jsonc-test$ jsonc < test.jsonc 
{/tmp/jsonc-test$ echo $?
0
```
It doesn't exit with a non-zero exit code and seems to just output just the valid part of the jsonc file, ignoring any invalid file contents.  Have I missed a step somewhere here?

**Comment by komkom** [comment]
Ok can you send me the invalid test.jsonc file. Best would be a short version to check?

**Comment by wwuck** [comment]
I just created the file with
```bash
echo "{{" > test.jsonc
```

**Comment by komkom** [comment]
Yes you are right error handling was missing for the cli version. I simplified the cmd pkg now. When testing with your file and with a valid file it works now. Can you double check?

**Comment by wwuck** [comment]
Thanks, I can get the exit code `1` when I run invalid content through jsonc.  I've added a Dockerfile in a PR so you can choose whether you would like to enable the Docker Hub auto-build and get a jsonc Docker image up on Docker Hub.

**Comment by komkom** [comment]
Ok thanks will take a look. But it will probably take a while.

**Comment by wwuck** [comment]
Thanks.  Meanwhile, I have built a docker image locally from the PR Dockerfile and have run a successful test using jsonc in a docker agent with Jenkins to do some basic linting on a json file with comments!

Thanks again for providing a useful tool.
