### ISSUE TITLE
Github pages site returns 404

### ISSUE THREAD

**Issue by chan-vince** [komkom/jsonc#8]
Just letting you know the site at https://komkom.github.io/ doesn't seem to exist anymore. Hopefully just a misconfiguration rather than intentional!

**Comment by chan-vince** [comment]
Ah just realised it's now at https://komkom.github.io/jsonc/

Unfortunately when googling for "jsonc", the first result isn't the right one. Feel free to close this, apologies.

**Comment by komkom** [comment]
Thank you for letting me know. I pushed the project from the top level down to its own folder. Unfortunately, searches probably still need to update.
